-- 완후율: APK 전환을 고려한 일정/기념일 데이터 구조
-- 기존 데이터는 삭제하지 않습니다. Supabase SQL Editor에서 1회 실행

alter table public.schedule_items
  add column if not exists reminder_minutes integer not null default 0;

-- 기념일과 자동 생성된 일정의 연결 정보
alter table public.schedule_items
  add column if not exists source_type text,
  add column if not exists source_id bigint;

create table if not exists public.family_anniversaries (
  id bigint generated by default as identity primary key,
  type text not null default '⭐ 기타',
  name text not null,
  month smallint not null check (month between 1 and 12),
  day smallint not null check (day between 1 and 31),
  original_date date,
  created_by text not null,
  created_at timestamptz not null default now()
);

alter table public.family_anniversaries enable row level security;

drop policy if exists "family anniversaries read" on public.family_anniversaries;
create policy "family anniversaries read" on public.family_anniversaries for select to anon, authenticated using (true);

drop policy if exists "family anniversaries insert" on public.family_anniversaries;
create policy "family anniversaries insert" on public.family_anniversaries for insert to anon, authenticated with check (true);

drop policy if exists "family anniversaries delete" on public.family_anniversaries;
create policy "family anniversaries delete" on public.family_anniversaries for delete to anon, authenticated using (true);

-- Realtime 등록은 이미 되어 있으면 오류가 날 수 있으므로 기존과 동일하게 별도 실행합니다.
-- alter publication supabase_realtime add table public.family_anniversaries;

-- 자료실: 기존 family-photos 버킷의 resources/ 폴더 사용
drop policy if exists "family resources read" on storage.objects;
create policy "family resources read" on storage.objects for select to anon, authenticated using (bucket_id = 'family-photos' and name like 'resources/%');

drop policy if exists "family resources upload" on storage.objects;
create policy "family resources upload" on storage.objects for insert to anon, authenticated with check (bucket_id = 'family-photos' and name like 'resources/%');

drop policy if exists "family resources delete" on storage.objects;
create policy "family resources delete" on storage.objects for delete to anon, authenticated using (bucket_id = 'family-photos' and name like 'resources/%');
