package com.woorijip.family;
import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.content.pm.ServiceInfo;import android.os.*;import androidx.annotation.NonNull;import androidx.core.app.NotificationCompat;import com.google.android.gms.location.*;import java.io.*;import java.net.*;import org.json.*;
public class NativeLocationService extends Service{
  static final String CH="woorijip_location";FusedLocationProviderClient client;LocationCallback callback;
  @Override public void onCreate(){super.onCreate();createChannel();}
  @Override public int onStartCommand(Intent i,int f,int id){Notification n=new NotificationCompat.Builder(this,CH).setSmallIcon(android.R.drawable.ic_menu_mylocation).setContentTitle("완후율 위치 공유").setContentText("가족에게 현재 위치를 공유하고 있어요").setOngoing(true).setPriority(NotificationCompat.PRIORITY_LOW).build();try{if(Build.VERSION.SDK_INT>=29)startForeground(7,n,ServiceInfo.FOREGROUND_SERVICE_TYPE_LOCATION);else startForeground(7,n);}catch(Exception e){android.util.Log.e("WoorijipGPS","startForeground",e);stopSelf();return START_NOT_STICKY;}startUpdates();return START_STICKY;}
  void startUpdates(){if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED&&checkSelfPermission(Manifest.permission.ACCESS_COARSE_LOCATION)!=PackageManager.PERMISSION_GRANTED){stopSelf();return;}client=LocationServices.getFusedLocationProviderClient(this);LocationRequest r=new LocationRequest.Builder(Priority.PRIORITY_HIGH_ACCURACY,10000).setMinUpdateIntervalMillis(5000).setMinUpdateDistanceMeters(5).build();callback=new LocationCallback(){@Override public void onLocationResult(@NonNull LocationResult lr){for(android.location.Location l:lr.getLocations())send(l.getLatitude(),l.getLongitude(),l.getAccuracy());}};try{client.requestLocationUpdates(r,callback,Looper.getMainLooper()).addOnFailureListener(e->android.util.Log.e("WoorijipGPS","requestLocationUpdates",e));client.getLastLocation().addOnSuccessListener(l->{if(l!=null)send(l.getLatitude(),l.getLongitude(),l.getAccuracy());});}catch(Exception e){android.util.Log.e("WoorijipGPS","location",e);}}
  void send(double lat,double lng,float acc){new Thread(()->{HttpURLConnection c=null;try{android.content.SharedPreferences p=getSharedPreferences("woorijip_native",0);String u=p.getString("user_name","");if(u.isEmpty()||!p.getBoolean("location_enabled",false))return;URL url=new URL("https://ogrqjrtulhrpuuqnymkh.supabase.co/rest/v1/family_locations?on_conflict=user_name");c=(HttpURLConnection)url.openConnection();c.setConnectTimeout(8000);c.setReadTimeout(8000);c.setRequestMethod("POST");c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");c.setRequestProperty("apikey","sb_publishable_gDdHqSfhl28EboFlW-dORA_XJrYZVqN");c.setRequestProperty("Authorization","Bearer sb_publishable_gDdHqSfhl28EboFlW-dORA_XJrYZVqN");c.setRequestProperty("Prefer","resolution=merge-duplicates,return=minimal");JSONObject o=new JSONObject();o.put("user_name",u);o.put("latitude",lat);o.put("longitude",lng);o.put("accuracy",acc);o.put("updated_at",new java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'",java.util.Locale.US).format(new java.util.Date()));try(OutputStream os=c.getOutputStream()){os.write(o.toString().getBytes("UTF-8"));}int code=c.getResponseCode();android.util.Log.d("WoorijipGPS","Supabase="+code+" user="+u);}catch(Exception e){android.util.Log.e("WoorijipGPS","send",e);}finally{if(c!=null)c.disconnect();}}).start();}
  void createChannel(){if(Build.VERSION.SDK_INT>=26){NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);nm.createNotificationChannel(new NotificationChannel(CH,"위치 공유",NotificationManager.IMPORTANCE_LOW));}}
  @Override public void onDestroy(){try{if(client!=null&&callback!=null)client.removeLocationUpdates(callback);}catch(Exception ignored){}super.onDestroy();}@Override public IBinder onBind(Intent i){return null;}
}
